[package]
name = "nolock"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["full"]
queues = []
hazard_ptr = ["queues"]
hash_trie = ["hazard_ptr"]
full = ["queues", "hazard_ptr", "hash_trie"]

[dependencies]

[dev-dependencies]
